### ISSUE TITLE
ASE change has lead to depreciated calculator functionality

### ISSUE THREAD

**Issue by SiliconScientist** [nec-research/alebrew#1]
Hello,

I was working through the tutorial inside `alebrew/examples/using_alebrew.ipynb` and I couldn't get past the line:

`from alebrew.datagen.references import SingleCalculatorReference`

The error takes us to `references.py`, which gives an error on line 159:

`from ase.calculators.general import Calculator`

I checked the ASE documentation and it looks like the file, `ase/calculators/general.py` has been removed in future versions of ASE. I went back to ASE version 3.22.1 and the `general.py` file is there, so I'll just have to revert until this issue is resolved.

**Comment by viktorzaverkin** [comment]
Thanks for bringing this up! For now, we explicitly set `ase==3.22.1` in our `alebrew-{cuda,cpu,mps}.yml` files.

We may not adjust for newer ASE versions since we plan to remove this dependency in future updates.
